import SignIn from "@/components/sign-in";
import "./globals.css";
import AuthStatus from "@/components/AuthStatus";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row text-black">
          <div className="w-4/5 h-screen p-3 bg-white">{children}</div>
          <div className="w-1/5 h-screen p-3 bg-black text-white">
            <h2 className="text-3xl">Next Client App</h2>
              <SessionProvider>
                <AuthStatus />
                <SignIn />
              </SessionProvider>
            <hr />
              {/* <Nav /> */}
          </div>
        </div>
      </body>
    </html>
  );
}